version: '2'
services:
    galileobooking-app:
        image: galileobooking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://galileobooking-mysql:3306/galileobooking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=galileobooking-elasticsearch:9300
        ports:
            - 8080:8080
    galileobooking-mysql:
        extends:
            file: mysql.yml
            service: galileobooking-mysql
    galileobooking-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: galileobooking-elasticsearch
